version: '3.8'

services:
  # Postgres Database Service
  postgresdb:
    image: postgres:15-alpine
    container_name: lms_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432" # my machine port:container port
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: lms_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    # Restricts memory usage so Redis never consumes all your system RAM
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

  # Node.js Application Service
  app:
    build: .
    container_name: lms_node_app
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy && npm run dev"
    ports:
      - "8000:3000" # my machine port:container port
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgresdb:5432/${DB_NAME}
      - REDIS_URL=redis://redis:6379
      - DB_HOST=postgresdb
      - CHOKIDAR_USEPOLLING=true
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
    depends_on:
      - postgresdb
      - redis
    volumes:
      - .:/app               
      - /app/node_modules
      - ./uploads:/app/dist/uploads

volumes:
  pgdata:
  redisdata: